version: '2'
services:
    jhipstersampleapplication2-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/jhipsterSampleApplication2/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=jhipsterSampleApplication2
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
